# Generated by Django 4.1.7 on 2023-04-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftEase', '0002_attendance_alter_employeedetail_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisordetail',
            old_name='user',
            new_name='sup',
        ),
    ]
