# Generated by Django 4.1.7 on 2023-04-09 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftEase', '0003_rename_user_supervisordetail_sup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='supervisordetail',
            name='contact',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
