# Generated by Django 4.1.7 on 2023-04-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftEase', '0004_alter_employeedetail_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supervisorDetail',
        ),
    ]
