# Generated by Django 4.1.7 on 2023-04-09 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShiftEase', '0007_alter_employeedetail_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
